name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  tests:
    name: tests / ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    needs: [pre-commit]
    env:
      PYTHONIOENCODING: utf-8

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy-3.7", "pypy-3.8"]
        include:
          - python: pypy-3.7
            nox-python: pypy3.7
          - python: pypy-3.8
            nox-python: pypy3.8

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install nox
        run: python -m pip install nox

      - name: Run test suite
        run: nox --force-color -v -s tests-${{ matrix.nox-python || matrix.python }} -- --color=yes -v
